import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import { useEffect, useState } from "react"

import Header from "../../components/header"
import Card from "../../components/card"
// import Image from 'next/image'
// import '../styles/globals.css'

export default function Jobs() {
  const [data, setData] = useState('')

  const router = useRouter();
  const path = router.query.path

  useEffect(() => {
    // setLoading(true)
    fetch('/api/jobs')
      .then((res) => res.json())
      .then((data) => {
        // setData(data)
        // setLoading(false)
        // debugger
        // console.log(data)
        setData(data)
      })
  }, [])

  return (
    <div>
      <Head>
        <title>Devjobs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header></Header>

        {data &&
          data.map(data => (
              data.path === router.query.path ? (
                <div key={data.id} className=''>
                  <section className='w-max min-w-[730px] h-[140px] my-0 mx-auto absolute top-28 left-1/2 -translate-x-2/4 flex items-center bg-dark-blue rounded-md'>
                    <div className='w-[140px] h-full'>
                      <Image src={data.logo} alt="" width={140} height={140} className='w-full h-auto rounded-tl-md rounded-bl-md' loading='lazy' />
                    </div>
                    <div className='ml-10'>
                      <p className='pb-3 font-bold text-2xl'>{data.company}</p>
                      <a href={data.website} target="_blank" rel="noopener noreferrer" className='text-base font-normal text-dark-gray'>{data.website}</a>
                    </div>
                    <a href={data.website} target="_blank" rel="noopener noreferrer" className='ml-auto mr-10 py-4 px-5 bg-white/10 rounded	font-bold text-base'>Company Site</a>
                  </section>

                  <section className='w-max max-w-[730px] my-0 mx-auto mt-32 py-12 px-11 bg-dark-blue rounded-md'>
                    <div className='flex justify-between items-center'>
                      <div>
                        <p className='text-base font-normal text-dark-gray'>{data.postedAt}<span> ・ </span>{data.contract}</p>
                        <h2 className='font-bold text-3xl my-2'>{data.position}</h2>
                        <p className='text-sm	font-bold text-violet'>{data.location}</p>
                      </div>
                      <a href={data.apply} target="_blank" rel="noopener noreferrer" className='py-4 px-5 bg-violet rounded	font-bold text-base'>Apply Now</a>
                    </div>
                    <p className='my-10 text-gray'>{data.description}</p>
                    <h3 className='font-bold text-xl'>Requirements</h3>
                    <p className='my-6 text-gray'>{data.requirements.content}</p>
                    <div className='ml-6'>
                      <ul className='mb-10 list-disc'>
                        {data.requirements.items &&
                          data.requirements.items.map(list => (
                            <li key={list} className='pb-2 pl-2 text-violet font-bold'>
                              <span className='text-gray font-normal'>{list}</span>
                            </li>
                          ))
                        }
                      </ul>
                    </div>
                    <h3 className='font-bold text-xl'>What You Will Do</h3>
                    <p className='my-6 text-gray'>{data.role.content}</p>
                    <div className='ml-6'>
                      <ol className='list-decimal'>
                        {data.role.items &&
                          data.role.items.map(list => (
                            <li key={list} className='pb-2 pl-2 text-violet font-bold'>
                              <span className='text-gray font-normal'>{list}</span>
                            </li>
                          ))
                        }
                      </ol>
                    </div>
                  </section>

                  <section className='w-full bg-dark-blue mt-20'>
                    <div className='max-w-[730px] my-0 mx-auto py-6 flex justify-between items-center'>
                      <div className=''>
                        <h4 className='font-bold text-xl'>{data.position}</h4>
                        <p className='pt-2 text-gray'>{data.company}</p>
                      </div>
                      <a href={data.apply} target="_blank" rel="noopener noreferrer" className='py-4 px-5 bg-violet rounded	font-bold text-base'>Apply Now</a>
                    </div>
                  </section>
                </div>
              ) : null
            )
          )
        }
      </main>
    </div>
  )
}
